### ISSUE TITLE
Pull a file or folder taking too long and doesn't show any status in statusbar.

### ISSUE THREAD

**Issue by Shababsoft** [mkloubert/vs-deploy#113]
Please can you check the reason of lag in pulling/deploying changes from/to remote using SFTP. At the moment a folder with 6-10 PHP files takes more than a minute to pull the changes. Whereas FileZilla takes around 2 seconds to pull same folder. I have noticed that plugin consume lot of processor during the pulling and deploying process.
At the moment I cannot find any status of a pull request in status bar / console until the success notification popup.

**Comment by mkloubert** [comment]
@Shababsoft 

This a "design problem".

The extension opens and closes a connection for each file, when pulling.

I will change this by putting anything into one session, the same way uplading works, what should reduce the time.

**Comment by Shababsoft** [comment]
@mkloubert  - Any update on this issue? The extension still takes ages to pull a folder with 3 javascript files,

**Comment by mkloubert** [comment]
@Shababsoft @popstas @adibpg

Because of the "design problem", I have decided to take the focus on a new extension, called [vscode-deploy-reloaded](https://marketplace.visualstudio.com/items?itemName=mkloubert.vscode-deploy-reloaded).

It is now able to pull files while one connection session, which should reduce the time extremly.

You can [try it out](https://github.com/mkloubert/vscode-deploy-reloaded) and give me a feedback if it works for you.

**It would take too much time to refactor this in the old extension.**

Issues of new extension [should be opened here](https://github.com/mkloubert/vscode-deploy-reloaded/issues).

The new wiki can be found [here](https://github.com/mkloubert/vscode-deploy-reloaded/wiki).

**Comment by Shababsoft** [comment]
@mkloubert - I have tried the new extension but still facing same issue. Pulling a javascript file (12KB) via STFP takes 35 - 50 seconds.
