### ISSUE TITLE
Deploy select files

### ISSUE THREAD

**Issue by zamkevich** [mkloubert/vs-deploy#142]
### Future request
In the new version of VSC have option 'Select multiple files" in the Explorer.
Can you add an option: "Deploy selected"?
Or better fix "Deploy current file / folder". Now it`s work only for first select file. And with new multiple file select option have confuses.

![image](https://user-images.githubusercontent.com/13717428/36083396-7d11b664-0ffd-11e8-919a-2dfcbce2e86e.png)

**Comment by mkloubert** [comment]
@zamkevich 

The problem is that the API currently does not support this or the feature is not well documented.

If I found out how to realize it, I will implemented in the new extension [vscode-deploy-reloaded](https://github.com/mkloubert/vscode-deploy-reloaded).

**Comment by zamkevich** [comment]
May be it's will help: 
[https://github.com/Microsoft/vscode/pull/41461](url)

**Comment by mkloubert** [comment]
@zamkevich 

Thank you very much for the help! :-)

I have implemented this in the recoded extension [vscode-deploy-reloaded](https://marketplace.visualstudio.com/items?itemName=mkloubert.vscode-deploy-reloaded), **which is available since version 0.46.0**.

![demo24](https://user-images.githubusercontent.com/4951215/36106568-02fd09ee-1018-11e8-9882-6d279776f57b.gif)

Most of the settings should be compatible with the ones of the old extension.

Have a look at the [wiki](https://github.com/mkloubert/vscode-deploy-reloaded/wiki#settings--) to get more information.

**Comment by zamkevich** [comment]
Thank you for Deploy — great work!
