### ISSUE TITLE
sftp performance improvement

### ISSUE THREAD

**Issue by unional** [mkloubert/vs-deploy#24]
I did a test with 7207 files.
`vs-deploy` takes 2 minutes and 2 seconds.
`webStorm` takes 1 minute and 17 seconds.
`winSCP` takes 45 seconds (with about 50 files less because they are in different directory).

Could the output log be a bottleneck? 🌷

**Comment by mkloubert** [comment]
I don't think that the output is the problem.

I think that the [ssh2-sftp-client](https://www.npmjs.com/package/ssh2-sftp-client) module I use (or [Node.js](https://nodejs.org/en/) as the underlying framework), might be the bottleneck. But all other alternatives are also using [ssh2](https://www.npmjs.com/package/ssh2) module as backend.

WebStorm and WinSCP use different frameworks and network libraries, which are much more optimized as JavaScript based code.

**Comment by mkloubert** [comment]
@unional I think that I have found the bottleneck!

The problem was, that I checked for an existing target directory by doing a `list()` for each file. That makes an upload very slow for a huge size of files as in your example.

**Now since version 4.21.0** I "cache" each target directory I have already checked, what would increase the speed of upload.

**Comment by unional** [comment]
Great news!
I'll test it out tomorrow. 🌷

**Comment by unional** [comment]
Verified!

It takes 1 minutes 15 seconds!
