### ISSUE TITLE
Notification of deployment

### ISSUE THREAD

**Issue by sebastus** [mkloubert/vs-deploy#42]
The popup notification and the terminal notification both require clicking something to make them go away. The status bar notification is non-specific. I'd like it better if the status bar notification told me which file it was deploying. As it is, "Deployment finished" just stays down there all the time. I can't tell when the messages changes because it's always the same.

**Comment by mkloubert** [comment]
**Since version 5.33.0** there is more information in the result item that apears in the status after a deployment:

![2017-03-04 00_38_01-notification of deployment issue 42 mkloubert_vs-deploy](https://cloud.githubusercontent.com/assets/4951215/23572930/dc5ee9c0-0072-11e7-8f7b-2bca2cf72d74.png)

If you would like to disapear that button automatic, you can use the new setting `hideDeployResultInStatusBarAfter` now:

```json
{
    "deploy": {
        // ...

        "hideDeployResultInStatusBarAfter": 30

        // ...
    }
}
```

In that example the button will disapear after `30 seconds`.

If you do not want to show a popup after a successful deployment and/or open the terminal when a deployment starts, you can set the settings `openOutputOnDeploy` and `showPopupOnSuccess` to `(false)`:

```json
{
    "deploy": {
        // ...

        "openOutputOnDeploy": false,
        "showPopupOnSuccess": false

        // ...
    }
}
```

**Comment by sebastus** [comment]
Love it!  Thanks!
