### ISSUE TITLE
Diff before uploading

### ISSUE THREAD

**Issue by iFarmGolems** [mkloubert/vs-deploy#46]
Hello,

Would it be possible to diff the uploaded file with the one on the server before every upload?

Example:

- Iam working on a file named code.js and I am uploading it on every save to the server via SFTP.
- Someone else changes code.js on a server, so it will be different from my last save.
- Now, I do not want to overwrite all the changes the person made, so I would like to get a diff screen or some information that this file was changed by someone else.
- If there are no conflicts, just upload the file.

**Comment by mkloubert** [comment]
Thanks for the great feature request!

**Since version 6.3.0** you can set the `diffBeforeDeploy` property to `(true)` in a target:

```json
{
    "deploy": {
        "targets": [
            {
                // ...

                "diffBeforeDeploy": true
            }
        ]
    }
}
```

This gif shows how it works:

![aufnahme_2017_03_17_11_27_13_800](https://cloud.githubusercontent.com/assets/4951215/24040163/65cb7f12-0b08-11e7-933c-d6cdde2bae61.gif)

**Comment by iFarmGolems** [comment]
Thank you very much!
