### ISSUE TITLE
I use a Mac and a PC on the same packages

### ISSUE THREAD

**Issue by sebastus** [mkloubert/vs-deploy#49]
I use "local" and "app" targets and the script & directory naming is different, of course. I'm probably "beyond the pale" on this one, so feel free to ignore. 

Why? Because the software I'm writing is multi-platform, of course. It also deploys and runs on Ubuntu, but I don't use that as a dev platform.

**Comment by mkloubert** [comment]
@sebastus 

Can you give a small example?

**Comment by sebastus** [comment]
Sure - on the Mac this is the target:

`{
                "type": "local",
                "name": "azureMonitorActivityLogs",
                "dir": "/Applications/Splunk/etc/apps/TA-Azure_Monitor_Activity_Logs",`

On the PC, the directory target would look like this:

`{
                "type": "local",
                "name": "azureMonitorActivityLogs",
                "dir": "c:\\program files\\Splunk\\etc\\apps\\TA-Azure_Monitor_Activity_Logs",`

**Comment by mkloubert** [comment]
@sebastus 

**Since version 7.5.0 you can use [placeholders](https://github.com/mkloubert/vs-deploy/wiki/values)** in

* [app](https://github.com/mkloubert/vs-deploy/wiki/target_app) targets
* [local](https://github.com/mkloubert/vs-deploy/wiki/target_local) targets
* [deploy operations](https://github.com/mkloubert/vs-deploy/wiki/targetoperations#open-)
* [zip](https://github.com/mkloubert/vs-deploy/wiki/target_zip) targets

now.

For your scenario it would look like this:

```json
{
    "deploy": {
        "values": [
            {
                "name": "outputDir", "description": "For Windows",

                "value": "c:\\program files\\Splunk\\etc\\apps\\TA-Azure_Monitor_Activity_Logs",
                "platforms": "win32"
            },
            {
                "name": "outputDir", "description": "For MacOS",

                "value": "/Applications/Splunk/etc/apps",
                "platforms": [ "darwin" ]
            }
        ],

        "targets": [
            {
                "name": "azureMonitorActivityLogs",
                "type": "local",

                "dir": "${outputDir}/TA-Azure_Monitor_Activity_Logs"
            }
        ]
    }
}
```

Another way to do this, is to define the `isFor` property, that defines a list of machines (by hostname) the value is for:

```json
{
    "deploy": {
        "values": [
            {
                "name": "outputDir", "description": "For Windows",

                "value": "c:\\program files\\Splunk\\etc\\apps\\TA-Azure_Monitor_Activity_Logs",
                "isFor": "myWindowsPC"
            },
            {
                "name": "outputDir", "description": "For MacOS",

                "value": "/Applications/Splunk/etc/apps",
                "isFor": [ "myMac" ]
            }
        ],

        // ...
    }
}
```

Or you can directly use `isFor` and `platforms` properties in a target, but this would require a target for each platform / machine (so the "placeholder solution" should be the better way):

```json
{
    "deploy": {
        "targets": [
            {
                "name": "azureMonitorActivityLogs",
                "type": "local",

                "isFor": [ "myWindowsPC" ],
                "dir": "c:\\program files\\Splunk\\etc\\apps\\TA-Azure_Monitor_Activity_Logs\\TA-Azure_Monitor_Activity_Logs"
            },

            {
                "name": "azureMonitorActivityLogs",
                "type": "local",

                "platforms": "darwin",
                "dir": "/Applications/Splunk/etc/apps/TA-Azure_Monitor_Activity_Logs"
            }
        ]
    }
}
```

Instead of using static values, you can [execute JavaScript code](https://github.com/mkloubert/vs-deploy/wiki/values#code-) to generate/provider a value.
