### ISSUE TITLE
Feature: provide a way to stop the deployment in the middle

### ISSUE THREAD

**Issue by unional** [mkloubert/vs-deploy#6]
For large project, this would be a great feature if we changed out mind (e.g. deploying to the wrong location).

**Comment by mkloubert** [comment]
**Since version 3.5.0** you can stop / cancel deployments:

![cancellation-demo](https://cloud.githubusercontent.com/assets/4951215/21284785/e0ce6e64-c426-11e6-8a43-8bca606efd45.gif)

As you see in demo, you have to click on the status bar item `Deploying...` at the bottom (left) to cancel a running operation.

**Comment by unional** [comment]
Ar, I see. 👍
