### ISSUE TITLE
Pull or compare shows the remote file as empty when it is not

### ISSUE THREAD

**Issue by rniswonger** [mkloubert/vs-deploy#65]
I have verified the FTP connection details are correct and the files are deployed to the proper folders. But even after successfully uploading a file, the Compare shows an empty file on remote and the Pull operation downloads a blank file.

Recently had this happen on a SiteGround shared server via FTP.

**Comment by mkloubert** [comment]
@rniswonger 

I know that [issue](https://github.com/mkloubert/vs-deploy/wiki/target_ftp#known-issues-).

Try to use [jsftp](https://github.com/sergi/jsftp) engine instead:

```json
{
    "deploy": {
        "targets": [
            {
                "type": "ftp",
                
                "engine": "jsftp",

                // ...
            }
        ]
    }
}
```

Have a look at the [wiki](https://github.com/mkloubert/vs-deploy/wiki/target_ftp#settings-) to check if all settings, that are required to connect to your server, are supported by that engine.

On the one hand, the old [ftp](https://github.com/mscdex/node-ftp) has a lot of supported options, but it is very buggy when downloading files.
I started an [issue here](https://github.com/mscdex/node-ftp/issues/180), but the development seems to have ended, because I got no answer until now.

[jsftp](https://github.com/sergi/jsftp) seems to be the much better choice if you do not need special options for the connection.

**Comment by rniswonger** [comment]
Thank you, I was not aware there was an alternative ftp engine. jsftp works great!
