### ISSUE TITLE
Same sring lines in ts file

### ISSUE THREAD

**Issue by sag3ll0** [mkloubert/vs-deploy#73]
Maybe is error?
![image](https://cloud.githubusercontent.com/assets/18505406/26177861/2e9c8d4c-3b64-11e7-9cfb-d8f175c41b1c.png)

**Comment by sag3ll0** [comment]
Maybe here need space beetwin Template and {
![image](https://cloud.githubusercontent.com/assets/18505406/26177950/8da8b996-3b64-11e7-9d90-f054975703de.png)

**Comment by mkloubert** [comment]
* [each](https://github.com/mkloubert/vs-deploy/wiki/target_each) and [map](https://github.com/mkloubert/vs-deploy/wiki/target_map) targets work similar, so I decided to use the same description
* for `browserTitle`, this will be done by `leading_space` in the placeholder: If a value is not an empty string, a leading space char is added before this value, otherwise the string behind `Template` is empty
